repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.9
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pytest-dev/pyproject-fmt
    rev: "v2.12.1"
    hooks:
      - id: pyproject-fmt
        # https://pyproject-fmt.readthedocs.io/en/latest/#calculating-max-supported-python-version
        additional_dependencies: ["tox>=4.9"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
